#!/usr/bin/env python3
"""AUC by context condition, rater and step-generator."""
import json, os, statistics as st
RATERS = [("agentflow-7b", "AgentFlow-7B"), ("qwen-base-7b", "Qwen 7B base"),
          ("qwen-32b-awq", "Qwen 32B"), ("qwen-72b-awq", "Qwen 72B")]
GENS = [("ctx_7bsteps.jsonl", "7B-gen"), ("ctx_32bsteps.jsonl", "32B-gen"), ("ctx_72bsteps.jsonl", "72B-gen")]
CONDS = [("c0", "step alone"), ("c1", "+prior steps"), ("c2", "+full traj"), ("c3", "+traj+GOLD")]
R = "/data/sakhaei/runs/"

def auc(pos, neg):
    if not pos or not neg: return None
    return sum(1.0 if p > n else 0.5 if p == n else 0.0 for p in pos for n in neg)/(len(pos)*len(neg))

def get(rows, m, c, s):
    out = []
    for r in rows:
        v = (r.get("ctx_ratings", {}).get(m) or {}).get(c)
        if r["stratum"] == s and v is not None: out.append(v)
    return out

data = {}
for fn, gl in GENS:
    data[gl] = [json.loads(l) for l in open(R+fn)] if os.path.exists(R+fn) else None

def show(metric, title):
    print(f"\n{'='*94}\n{title}")
    for _, gl in GENS:
        rows = data.get(gl)
        if not rows: continue
        print(f"\n  --- steps generated by {gl} ---")
        print(f"  {'rater':16s}" + "".join(f"{cl:>14s}" for _, cl in CONDS))
        for m, ml in RATERS:
            cells = []
            for c, _ in CONDS:
                dead, mid, gold = get(rows,m,c,"dead"), get(rows,m,c,"mid"), get(rows,m,c,"gold")
                if not (mid and gold and dead): cells.append("n/a"); continue
                v = auc(gold, mid) if metric == "gm" else auc(mid+gold, dead)
                cells.append(f"{v:.3f}" if v is not None else "n/a")
            if any(x != "n/a" for x in cells):
                print(f"  {ml:16s}" + "".join(f"{x:>14s}" for x in cells))

show("gm", "AUC gold vs mid -- 'was it actually the answer?'  (0.5 = coin flip)")
show("dead", "AUC informative vs dead -- 'did anything come back?'")
