#!/usr/bin/env python3
"""4 generators x 4 raters x 4 context conditions on one task, clean labels.

  python ctx_grid_any.py <task-tag> <ratings-prefix>
     e.g.  python ctx_grid_any.py bamboogle ctx2_bb      (files ctx2_bb_af7b.jsonl ...)
           python ctx_grid_any.py 2wiki     ctx2_gen2

PATCHED (MAReasoning) 2026-09-18: supersedes ctx_grid4.py, whose inputs carried the
substring gold-label bug (see build_gen.py). Prints n per stratum next to the AUCs so tiny
strata are visible.
"""
import json, os, sys, statistics as st

RATERS = [("agentflow-7b", "AgentFlow-7B"), ("qwen-base-7b", "Qwen 7B base"),
          ("qwen-32b-awq", "Qwen 32B"), ("qwen-72b-awq", "Qwen 72B")]
GENS = [("af7b", "AgentFlow-7B"), ("qw7b", "Qwen 7B base"), ("32b", "Qwen 32B"), ("72b", "Qwen 72B")]
CONDS = [("c0", "step alone"), ("c1", "+prior"), ("c2", "+full traj"), ("c3", "+traj+GOLD")]
R = "/data/sakhaei/runs/"
TAG, PFX = sys.argv[1], sys.argv[2]

def auc(pos, neg):
    if not pos or not neg: return None
    return sum(1.0 if p > n else 0.5 if p == n else 0.0 for p in pos for n in neg) / (len(pos)*len(neg))

def load(g):
    p = f"{R}{PFX}_{g}.jsonl"
    return [json.loads(l) for l in open(p)] if os.path.exists(p) else None

def vals(rows, rater, cond, stratum):
    out = []
    for r in rows:
        v = (r.get("ctx_ratings", {}).get(rater) or {}).get(cond)
        if r["stratum"] == stratum and v is not None: out.append(v)
    return out

def cell(rows, rater, cond, mode):
    dead, mid, gold = (vals(rows, rater, cond, s) for s in ("dead", "mid", "gold"))
    if mode == "hard": return auc(gold, mid)
    if mode == "easy": return auc(mid + gold, dead)
    return (st.mean(mid) if mid else None)

def block(mode, title):
    print("=" * 96); print(f"[{TAG}] {title}")
    for g, gl in GENS:
        rows = load(g)
        print(f"\n  --- steps generated by {gl} ---")
        if not rows: print("      (no data)"); continue
        ns = {s: sum(1 for r in rows if r["stratum"] == s) for s in ("dead", "gold", "mid")}
        print(f"      n={len(rows)} (dead {ns['dead']} / gold {ns['gold']} / mid {ns['mid']})")
        print("  " + f"{'rater':16s}" + "".join(f"{cl:>14s}" for _, cl in CONDS))
        for m, ml in RATERS:
            line = f"  {ml:16s}"
            for c, _ in CONDS:
                v = cell(rows, m, c, mode)
                line += f"{('  n/a' if v is None else f'{v:.3f}'):>14s}"
            print(line)

block("hard", "AUC gold vs mid -- 'was it actually the answer?'   (0.5 = coin flip)")
print(); block("easy", "AUC informative vs dead -- 'did anything come back?'")
print(); block("mid", "MID stratum mean rating (0-4) -- how convincing the non-answer steps look")
