#!/usr/bin/env python3
"""Full design: 4 generators x 4 raters x 4 context conditions = 64 cells.

Every generator column is a SINGLE model on a SINGLE task (2wiki), so nothing is pooled.
This supersedes the earlier "7B-generated" column, which mixed the trained and base 7B and
mixed three tasks.
"""
import json, os, statistics as st

RATERS = [("agentflow-7b", "AgentFlow-7B"), ("qwen-base-7b", "Qwen 7B base"),
          ("qwen-32b-awq", "Qwen 32B"), ("qwen-72b-awq", "Qwen 72B")]
GENS = [("ctx_af7bsteps.jsonl", "AgentFlow-7B"), ("ctx_qw7bsteps.jsonl", "Qwen 7B base"),
        ("ctx_32bsteps.jsonl", "Qwen 32B"), ("ctx_72bsteps.jsonl", "Qwen 72B")]
CONDS = [("c0", "step alone"), ("c1", "+prior"), ("c2", "+full traj"), ("c3", "+traj+GOLD")]
R = "/data/sakhaei/runs/"

def auc(pos, neg):
    if not pos or not neg: return None
    return sum(1.0 if p > n else 0.5 if p == n else 0.0 for p in pos for n in neg) / (len(pos)*len(neg))

def load(fn):
    p = R + fn
    return [json.loads(l) for l in open(p)] if os.path.exists(p) else None

def vals(rows, rater, cond, stratum):
    out = []
    for r in rows:
        v = (r.get("ctx_ratings", {}).get(rater) or {}).get(cond)
        if r["stratum"] == stratum and v is not None: out.append(v)
    return out

def cell(rows, rater, cond, mode):
    if not rows: return None
    dead, mid, gold = (vals(rows, rater, cond, s) for s in ("dead", "mid", "gold"))
    if not (dead and mid and gold): return None
    return auc(gold, mid) if mode == "hard" else auc(mid + gold, dead)

def block(mode, title):
    print("=" * 94); print(title)
    for fn, gl in GENS:
        rows = load(fn)
        print(f"\n  --- steps generated by {gl} ---")
        if not rows:
            print("      (no data)"); continue
        ns = {s: sum(1 for r in rows if r["stratum"] == s) for s in ("dead","gold","mid")}
        print(f"      n={len(rows)} (dead {ns['dead']} / gold {ns['gold']} / mid {ns['mid']})")
        print("  " + f"{'rater':16s}" + "".join(f"{cl:>14s}" for _, cl in CONDS))
        for m, ml in RATERS:
            line = f"  {ml:16s}"
            for c, _ in CONDS:
                v = cell(rows, m, c, mode)
                line += f"{('  n/a' if v is None else f'{v:.3f}'):>14s}"
            print(line)

block("hard", "AUC gold vs mid -- 'was it actually the answer?'   (0.5 = coin flip)")
print()
block("easy", "AUC informative vs dead -- 'did anything come back?'")
