#!/usr/bin/env python3
"""Mean +- std rating per (generator, rater, stratum, context), plus AUCs.

  python stats7b.py <prefix> <gen-tag> [<gen-tag> ...]      e.g. stats7b.py ctx7_bb af7b qw7b

Reads /data/sakhaei/runs/<prefix>_<gen>.jsonl written by rate_ctx.py.
"""
import json, os, sys, statistics as st

RATERS = [("agentflow-7b", "AgentFlow-7B"), ("qwen-base-7b", "Qwen-7B base"), ("qwen-32b-awq", "Qwen-32B AWQ")]
GENL = {"af7b": "AgentFlow-7B", "qw7b": "Qwen-7B base", "32b": "Qwen-32B", "72b": "Qwen-72B"}
CONDS = [("c0", "step alone"), ("c1", "+prior steps"), ("c2", "+full traj"), ("c3", "+traj+gold")]
R = "/data/sakhaei/runs/"
PFX, GENS = sys.argv[1], sys.argv[2:]

def auc(pos, neg):
    if not pos or not neg: return None
    return sum(1.0 if p > n else 0.5 if p == n else 0.0 for p in pos for n in neg) / (len(pos) * len(neg))

def ms(v):
    if not v: return "   n/a     "
    return f"{st.mean(v):.2f}±{(st.pstdev(v) if len(v) > 1 else 0):.2f}"

for g in GENS:
    p = f"{R}{PFX}_{g}.jsonl"
    if not os.path.exists(p): print(f"(no file {p})"); continue
    rows = [json.loads(l) for l in open(p)]
    ns = {s: sum(1 for r in rows if r["stratum"] == s) for s in ("dead", "gold", "mid")}
    print("=" * 92)
    print(f"steps generated by {GENL.get(g, g)}   n={len(rows)}  dead={ns['dead']} gold={ns['gold']} mid={ns['mid']}")
    for m, ml in RATERS:
        print(f"\n  rater: {ml}")
        print(f"  {'context':14s} {'dead':>11s} {'mid':>11s} {'gold':>11s}   {'AUC gold|mid':>12s} {'AUC live|dead':>13s}  {'missing':>7s}")
        for c, cl in CONDS:
            v = {s: [] for s in ns}; miss = 0
            for r in rows:
                x = (r.get("ctx_ratings", {}).get(m) or {}).get(c)
                if x is None: miss += 1
                else: v[r["stratum"]].append(x)
            a1 = auc(v["gold"], v["mid"]); a2 = auc(v["gold"] + v["mid"], v["dead"])
            print(f"  {cl:14s} {ms(v['dead']):>11s} {ms(v['mid']):>11s} {ms(v['gold']):>11s}   "
                  f"{('n/a' if a1 is None else f'{a1:.3f}'):>12s} {('n/a' if a2 is None else f'{a2:.3f}'):>13s}  {miss:>7d}")
    # rater agreement on the same steps, c0
    both = [((r["ctx_ratings"].get("agentflow-7b") or {}).get("c0"), (r["ctx_ratings"].get("qwen-base-7b") or {}).get("c0"))
            for r in rows if r.get("ctx_ratings")]
    both = [(a, b) for a, b in both if a is not None and b is not None]
    if len(both) > 2:
        ma, mb = st.mean(a for a, _ in both), st.mean(b for _, b in both)
        cov = sum((a - ma) * (b - mb) for a, b in both)
        sa = (sum((a - ma) ** 2 for a, _ in both)) ** .5; sb = (sum((b - mb) ** 2 for _, b in both)) ** .5
        print(f"\n  rater agreement, step alone: pearson r={cov / (sa * sb) if sa and sb else float('nan'):.3f}, "
              f"exact same integer on {sum(1 for a, b in both if a == b)}/{len(both)} steps")
